package proyecto.clinica_dental_calderon.Form;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.Timer;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Yber-M;
 */
public class BarraProgreso extends javax.swing.JFrame {
    
    String diente = "/images/diente.png";
    String logo = "/images/LogoDentalCircle.png";
    ImageIcon Logo = new ImageIcon(BarraProgreso.class.getResource(logo));
    
    Timer time;
    
    

    Random random = new Random();
    private Timer timerProgreso;
    private Timer timerPuntos;
    private final int delayProgreso = 100; // Retraso para la barra de progreso
    private final int delayPuntos = 200; // Retraso para los puntos
    private int contadorPuntos = 0;

    public BarraProgreso() {
        ActionListener alProgreso = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    actualizarProgreso();
                } catch (SQLException ex) {
                    Logger.getLogger(BarraProgreso.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };

        ActionListener alPuntos = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarPuntos();
            }
        };

        timerProgreso = new Timer(delayProgreso, alProgreso);
        timerPuntos = new Timer(delayPuntos, alPuntos);

        this.setUndecorated(true);
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));

        timerProgreso.start();
        timerPuntos.start();
        
        this.setIconImage(new ImageIcon(BarraProgreso.class.getResource(diente)).getImage());
        
        lblLogo.setIcon(Logo);
    }

    private void actualizarProgreso() throws SQLException {
        if (pgbCarga.getValue() < 100) {
            int incremento = 1 + random.nextInt(6);
            pgbCarga.setValue(Math.min(pgbCarga.getValue() + incremento, 100));

        } else {
            timerProgreso.stop();
            AbrirSistema();
        }
    }

    private void actualizarPuntos() {
        String puntos = ".".repeat(contadorPuntos % 4);
        lblCarga.setText("Cargando" + puntos);
        contadorPuntos++;
    }

    public void AbrirSistema() throws SQLException {
        F_Sistema sistema = new F_Sistema();
        
        sistema.setVisible(true);

        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarga = new javax.swing.JLabel();
        lblBievenido1 = new javax.swing.JLabel();
        pgbCarga = new javax.swing.JProgressBar();
        lblBievenido2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarga.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        lblCarga.setForeground(new java.awt.Color(255, 255, 255));
        lblCarga.setText("Cargando...");
        getContentPane().add(lblCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 210, 60));

        lblBievenido1.setFont(new java.awt.Font("Lucida Sans", 1, 74)); // NOI18N
        lblBievenido1.setForeground(new java.awt.Color(52, 139, 209));
        lblBievenido1.setText("DentalSoft");
        getContentPane().add(lblBievenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 410, 110));
        getContentPane().add(pgbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 640, 30));

        lblBievenido2.setFont(new java.awt.Font("Lucida Sans", 1, 74)); // NOI18N
        lblBievenido2.setForeground(new java.awt.Color(121, 196, 255));
        lblBievenido2.setText("BIENVENIDO");
        getContentPane().add(lblBievenido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 480, 110));

        lblLogo.setText("jLabel1");
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 269, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarraProgreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBievenido1;
    private javax.swing.JLabel lblBievenido2;
    private javax.swing.JLabel lblCarga;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JProgressBar pgbCarga;
    // End of variables declaration//GEN-END:variables
}
